export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const ADD_CENTER_SUCCESS = 'ADD_CENTER_SUCCESS';
export const ADD_CENTER_FAILURE = 'ADD_CENTER_FAILURE';
